### ISSUE TITLE
Feature request, complete example documentation.

### ISSUE THREAD

**Issue by JonRowe** [absinthe-graphql/absinthe-socket#27]
Hi, I'm new to this project and struggling to understand from the individual function docs how to use this. Is there a chance someone with better knowledge could complete the Readme with an example that actually connects to an absinthe server, sends a query (preferably a subscription) and does something with the response?

**Comment by alukito** [comment]
Hi, I'm also new, but I find these examples to be working.

1. Setup the apollo client using this [apollo guide](https://www.apollographql.com/docs/react/essentials/get-started.html)
2. Change the ApolloClient implementation using @absinthe-socket/socket-apollo-link using the [readme](https://github.com/absinthe-graphql/absinthe-socket/blob/master/packages/socket-apollo-link/README.md). Note that since we're changing the apollo link to use for the client, we could not use `apollo-boost` but we need the individual libraries like `apollo-client` and `apollo-cache-inmemory`

This is using React, so maybe you need to adjust accordingly when using Elm. Hope that helps.

**Comment by JonRowe** [comment]
@alukito Thanks but I'm not using Apollo, so I'm still looking for a complete example for the base socket implementation.

**Comment by JonRowe** [comment]
Closing in preference to #28
