### ISSUE TITLE
Is this the preferred Apollo link solution for Absinthe subscriptions?

### ISSUE THREAD

**Issue by benjarwar** [absinthe-graphql/absinthe-socket#53]
We're using Absinthe with subscriptions on our BE, and Apollo Client on our FE application. Wondering if this library includes implementation details specific to Absinthe that makes it preferable over [Apollo's documentation](https://www.apollographql.com/docs/react/data/subscriptions/) and using [apollo-link-ws](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-ws).

**Comment by benwilson512** [comment]
Hey @benjarwar. The purpose of this library is to wrap `phoenix.js` so that you can use subscriptions with the normal phoenix websocket handler. If you try to use the apollo-link-ws library w/ Phoenix it won't work, because they use different websocket protocols.

There is an Elixir library out there that claims to support the apollo-link-ws protocol you could also look at. The Absinthe core team is currently evaluating whether we should bring that library in house, since we currently lack any JS developer who can keep this library up to date.

**Comment by benjarwar** [comment]
@benwilson512 thanks for the very prompt reply, and exactly the information we needed! We've been testing `absinthe-socket` and it's working well for us so far. Appreciate the work!

**Comment by benwilson512** [comment]
Glad I could help!

**Comment by tlvenn** [comment]
I am not really sure what you would gain by trying to leverage `apollo-link-ws` to work with Absinthe / phoenix. Apollo link is however super useful and we do support it fully with `@absinthe/socket-apollo-link`.

**Comment by arjan** [comment]
I think @benwilson512 explains it pretty well. This is a JS package in the the Absinthe project that is currently not maintained (it seems). E.g. to make it work with Apollo 3 requires a bit of monkey-patching currently. I agree that the less JS code in the absinthe project, the better :-)

**Comment by tlvenn** [comment]
Ya I realized after my comment that quite a few things have changed with Apollo 3 and their integration of Apollo Link ...
@mgtitimoli is actually working on an update of our JS packages which should come out pretty soon as far as I know.
He will likely have a look at both our Relay and Apollo integration at that time.

**Comment by arjan** [comment]
FWIW, I solved it by creating an `apollo-link.js` file which re-exports the ApolloLink:

```
// this export is here for interop with @absinthe/socket-apollo-link
export { ApolloLink } from '@apollo/client'
```

**Comment by benwilson512** [comment]
@tlvenn if someone can do a pass on the absinthe-socket library that'd probably be great, but the issue from the perspective of the Absinthe core team is that:

1) Absinthe Socket cannot be kept up to date by anyone on the core team
2) Absinthe Socket requires that we ship dedicated custom versions of GraphiQL that use Absinthe socket.

If we ship a version of `absinthe_phoenix` that supports apollo-ws natively, then both of those issues go away. It's still probably great if absinthe-socket exists for people who don't want to have to add a new socket transport, but at least if we do the socket transport stuff it's just Elixir code, and that makes it easier for the Elixir community around Absinthe to keep it up to date.

**Comment by Stefano1990** [comment]
@benwilson512 has the core team decided on apollo-ws? Is this something that is on the roadmap?

Unfortunately, the current state of absinthe-socket means that it can de facto not be used in any new vue3 project (since core-js v2 does not work with webpack 5 i believe?). This in turn would mean that absinthe can not be used by anybody who uses vue3 with apollo, which is the standard for vue (the vue-apollo github has 7.7k users vs 7 vor the vue-relay github repo).

**Comment by benjarwar** [comment]
@benwilson512 we're also interested in this, as it seems unwise to rely on these unmaintained JS libs. You also previously said:

> There is an Elixir library out there that claims to support the apollo-link-ws protocol you could also look at

Mind pointing us to that? Haven't found anything. Thanks in advance!

**Comment by mwhitworth** [comment]
> > There is an Elixir library out there that claims to support the apollo-link-ws protocol you could also look at
> 
> Mind pointing us to that? Haven't found anything. Thanks in advance!

I think the library in question is [absinthe_graphql_ws](https://github.com/geometerio/absinthe_graphql_ws)
